verb1 = input("Ingresa un verbo un primera persona: ")
noun = input("Ingresa un sustantivo: ")
verb2 = input("Ingresa un verbo un primera persona: ")
verb3 = input("Ingresa un verbo un primera persona: ") 

print("")
print("Cada vez que",verb1," en ti,")
print("mis ojos rompen en ",noun,";")
print("y muy triste me",verb2,",")
print("¿por qué te ",verb3," tanto?")